import { TimeSlot, Track, RequestTicket } from './types';
import bossaNovaCover from './assets/images/bossa_nova_cover_1788508105737.jpg';

export const DEFAULT_TRACK_COVER = bossaNovaCover;

export const getTrackCover = (track?: Track | null): string => {
  if (track?.coverUrl) return track.coverUrl;
  if (track?.cover) return track.cover;
  return bossaNovaCover;
};

export const INITIAL_TRACK: Track = {
  id: 'track-1',
  title: 'Chega de Saudade (Bossa Nova Cover)',
  artist: 'Mats & My',
  album: 'Mats & My Bossa Nova Covers',
  duration: '03:45',
  durationSec: 225,
  coffeePairing: 'Cold Brew Cam Vàng & V60 Pour-over',
  genre: 'Bossa Nova Acoustic',
  coverUrl: bossaNovaCover,
};

export const INITIAL_TIME_SLOTS: TimeSlot[] = [
  {
    id: 'slot-current',
    slotNumber: 'SLOT #2',
    name: 'Cộng Đồng Buổi Sáng',
    timeRange: '9 AM – 11 AM',
    description: 'Tinh tế và thư giãn. Tuyển chọn V-Indie & acoustic cho cuộc trò chuyện và kết nối năng lượng.',
    accentColor: '#FEBC11',
    badgeBg: '#FEBC11',
    badgeText: '#0D0D0E',
    playlists: [
      {
        id: 'v-indie',
        title: 'Bossa Nova & Indie Acoustic',
        slotId: 'slot-current',
        slotName: '9 AM – 11 AM',
        description: 'Bossa Nova mộc mạc và Acoustic sâu lắng bên tách cà phê.',
        trackCount: 42,
        duration: '2H 45M',
        icon: 'fa-music',
        accentColor: '#FEBC11',
        isNowPlaying: true,
        tracks: [
          { id: 't-bossa', title: 'Chega de Saudade', artist: 'Mats & My', duration: '03:45', durationSec: 225, coffeePairing: 'Cold Brew Cam Vàng', coverUrl: bossaNovaCover },
          { id: 't-1', title: 'Lời Nhắn', artist: 'Quyếch', duration: '03:45', durationSec: 225, coffeePairing: 'Cà phê Muối', coverUrl: bossaNovaCover },
          { id: 't-2', title: 'Mùa Hè Của Em', artist: 'Vũ.', duration: '04:12', durationSec: 252, coffeePairing: 'Cold Brew Mơ Rừng', coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=600&auto=format&fit=crop&q=80' },
          { id: 't-3', title: 'Chuyện Những Người Yêu Xa', artist: 'Vũ Cát Tường', duration: '03:58', durationSec: 238, coffeePairing: 'Latte Hạnh Nhân', coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80' },
          { id: 't-4', title: 'Đi Về Phía Mưa', artist: 'Thái Đinh', duration: '04:20', durationSec: 260, coffeePairing: 'Pour-over Ethiopia', coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80' },
          { id: 't-5', title: 'Có Những Ngày Ơi', artist: 'Trần Duy Đạt', duration: '03:32', durationSec: 212, coffeePairing: 'Cà phê Sữa Tươi Sương Mai', coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80' },
        ],
      },
      {
        id: 'soft-pop-hits',
        title: 'Soft Pop Hits',
        slotId: 'slot-current',
        slotName: '9 AM – 11 AM',
        description: 'Giai điệu bắt tai êm dịu, khởi đầu ngày làm việc.',
        trackCount: 38,
        duration: '2H 10M',
        icon: 'fa-cloud-sun',
        accentColor: '#FEBC11',
        tracks: [
          { id: 't-6', title: 'Until I Found You', artist: 'Stephen Sanchez', duration: '02:58', durationSec: 178, coffeePairing: 'Cappuccino Kem Béo' },
          { id: 't-7', title: 'Golden Hour (Acoustic)', artist: 'JVKE', duration: '03:29', durationSec: 209, coffeePairing: 'Americano Đá' },
          { id: 't-8', title: 'Here With Me', artist: 'd4vd', duration: '04:02', durationSec: 242, coffeePairing: 'Flat White' },
          { id: 't-9', title: 'Double Take (Stripped)', artist: 'dhruv', duration: '02:51', durationSec: 171, coffeePairing: 'Mocha Nóng' },
        ],
      },
      {
        id: 'lofi-lau-fai',
        title: 'Lofi Lâu Fai',
        slotId: 'slot-current',
        slotName: '9 AM – 11 AM',
        description: 'Nhịp không lời êm đềm, hợp với Pour-over V60.',
        trackCount: 55,
        duration: '3H 20M',
        icon: 'fa-headphones-simple',
        accentColor: '#C084FC',
        tracks: [
          { id: 't-10', title: 'Roastery Morning Rain', artist: 'Gate 7 Sound Lab', duration: '03:15', durationSec: 195, coffeePairing: 'Pour-over V60 Kenya' },
          { id: 't-11', title: 'Coffee Beans & Tape Hiss', artist: 'Kavv', duration: '02:44', durationSec: 164, coffeePairing: 'Espresso Tonic' },
          { id: 't-12', title: 'Old Quarter Lo-fi', artist: 'Hanoi Tape', duration: '03:30', durationSec: 210, coffeePairing: 'Bạc Xỉu 3 Tầng' },
        ],
      },
      {
        id: 'indie-pop',
        title: 'Indie Pop',
        slotId: 'slot-current',
        slotName: '9 AM – 11 AM',
        description: 'Sáng tạo & năng lượng trẻ trung cho không gian quán.',
        trackCount: 34,
        duration: '1H 55M',
        icon: 'fa-guitar',
        accentColor: '#F472B6',
        tracks: [
          { id: 't-13', title: 'Cà phê Một Mình', artist: 'Thịnh Suy', duration: '03:40', durationSec: 220, coffeePairing: 'Cà phê Phin Truyền Thống' },
          { id: 't-14', title: 'Say Goodbye', artist: 'Trang ft. Tiên Tiên', duration: '03:15', durationSec: 195, coffeePairing: 'Cold Brew Cam Vàng' },
          { id: 't-15', title: 'Dấu Mưa (Acoustic 2024)', artist: 'Trung Quân', duration: '04:05', durationSec: 245, coffeePairing: 'Matcha Espresso' },
        ],
      },
    ],
  },
  {
    id: 'slot-morning',
    slotNumber: 'SLOT #1',
    name: 'Khách Buổi Sáng (Tỉnh Thức Sớm)',
    timeRange: '6 AM – 9 AM',
    description: 'Thức dậy nhẹ nhàng. Nhạc jazz và acoustic tràn đầy sinh khí cho ngày mới.',
    accentColor: '#FEBC11',
    badgeBg: '#202026',
    badgeText: '#FEBC11',
    playlists: [
      {
        id: 'ca-phe-quan-quen',
        title: 'Cà Phê Quán Quen',
        slotId: 'slot-morning',
        slotName: '6 AM – 9 AM',
        description: 'Acoustic sáng sớm mộc mạc.',
        trackCount: 32,
        duration: '2h 15m',
        icon: 'fa-coffee',
        accentColor: '#FEBC11',
        tracks: [
          { id: 't-16', title: 'Bình Minh Trên Phố', artist: 'Hanoi Acoustic Trio', duration: '03:22', durationSec: 202, coffeePairing: 'Phin Đen Nóng' },
          { id: 't-17', title: 'Tỉnh Thức Bên Tách Nâu', artist: 'Roastery Ensemble', duration: '04:10', durationSec: 250, coffeePairing: 'Nâu Lắc Bọt Sữa' },
        ],
      },
      {
        id: 'coffeehouse-chill',
        title: 'Coffeehouse Chill',
        slotId: 'slot-morning',
        slotName: '6 AM – 9 AM',
        description: 'Êm dịu & thư thái đón bình minh.',
        trackCount: 28,
        duration: '1h 48m',
        icon: 'fa-mug-hot',
        accentColor: '#FEBC11',
        tracks: [
          { id: 't-18', title: 'Sunrise Over West Lake', artist: 'Acoustic Soul', duration: '03:45', durationSec: 225, coffeePairing: 'Americano Nóng' },
          { id: 't-19', title: 'Morning Dew Drops', artist: 'Sweet Acoustic', duration: '03:12', durationSec: 192, coffeePairing: 'Latte Mật Ong' },
        ],
      },
      {
        id: 'chillhop-boost',
        title: 'Chillhop Boost',
        slotId: 'slot-morning',
        slotName: '6 AM – 9 AM',
        description: 'Giai điệu tích cực tỉnh táo.',
        trackCount: 46,
        duration: '3h 05m',
        icon: 'fa-bolt',
        accentColor: '#FEBC11',
        tracks: [
          { id: 't-20', title: 'Espresso Machine Kick', artist: 'Beat Roaster', duration: '02:50', durationSec: 170, coffeePairing: 'Double Espresso' },
          { id: 't-21', title: 'Fresh Brew Energy', artist: 'Lofi Flow', duration: '03:05', durationSec: 185, coffeePairing: 'Cold Brew Đậm Vị' },
        ],
      },
      {
        id: 'bossa-nova-jazz',
        title: 'Bossa Nova Jazz',
        slotId: 'slot-morning',
        slotName: '6 AM – 9 AM',
        description: 'Ấm áp, acoustic êm dịu đón ngày mới.',
        trackCount: 36,
        duration: '2h 30m',
        icon: 'fa-martini-glass-citrus',
        accentColor: '#FEBC11',
        tracks: [
          { id: 't-22', title: 'Girl from Ipanema (Acoustic)', artist: 'Astrud Trio', duration: '03:35', durationSec: 215, coffeePairing: 'Cappuccino Quế' },
          { id: 't-23', title: 'Desafinado Guitar Sessions', artist: 'Joao Roastery', duration: '04:15', durationSec: 255, coffeePairing: 'Cortado' },
        ],
      },
    ],
  },
  {
    id: 'slot-lunch',
    slotNumber: 'SLOT #3',
    name: 'Trưa & Chiều (Focus & Deep Work)',
    timeRange: '11 AM – 3 PM',
    description: 'Đa dạng và tập trung. Sự kết hợp lo-fi và ambient cho làm việc hiệu quả.',
    accentColor: '#3B82F6',
    badgeBg: '#202026',
    badgeText: '#60A5FA',
    playlists: [
      {
        id: 'lofi-deep-focus',
        title: 'Lofi Deep Focus',
        slotId: 'slot-lunch',
        slotName: '11 AM – 3 PM',
        description: 'Làm việc không xao nhãng.',
        trackCount: 60,
        duration: '4h 12m',
        icon: 'fa-laptop-code',
        accentColor: '#3B82F6',
        tracks: [
          { id: 't-24', title: 'Code & Caffeine', artist: 'Dev Beats', duration: '03:10', durationSec: 190, coffeePairing: 'Cold Brew Trực Tiếp' },
          { id: 't-25', title: 'Deep Flow State', artist: 'Theta Wave', duration: '04:30', durationSec: 270, coffeePairing: 'Americano Không Đường' },
        ],
      },
      {
        id: 'acoustic-ambient',
        title: 'Acoustic Ambient',
        slotId: 'slot-lunch',
        slotName: '11 AM – 3 PM',
        description: 'Khoáng đạt rộng mở.',
        trackCount: 35,
        duration: '2h 40m',
        icon: 'fa-wind',
        accentColor: '#3B82F6',
        tracks: [
          { id: 't-26', title: 'Echoes of Timber', artist: 'Hollow Sound', duration: '03:55', durationSec: 235, coffeePairing: 'Pour-over Costa Rica' },
        ],
      },
      {
        id: 'brain-food',
        title: 'Brain Food',
        slotId: 'slot-lunch',
        slotName: '11 AM – 3 PM',
        description: 'Nuôi dưỡng ý tưởng.',
        trackCount: 48,
        duration: '3h 15m',
        icon: 'fa-brain',
        accentColor: '#3B82F6',
        tracks: [
          { id: 't-27', title: 'Synapses Sparking', artist: 'Neural Cafe', duration: '03:18', durationSec: 198, coffeePairing: 'Flat White Yến Mạch' },
        ],
      },
      {
        id: 'khong-loi-bat-hu',
        title: 'Không Lời Bất Hủ',
        slotId: 'slot-lunch',
        slotName: '11 AM – 3 PM',
        description: 'Cảm xúc lắng đọng.',
        trackCount: 40,
        duration: '2h 50m',
        icon: 'fa-record-vinyl',
        accentColor: '#3B82F6',
        tracks: [
          { id: 't-28', title: 'Nắng Thủy Tinh (Guitar Solo)', artist: 'Trịnh Chill', duration: '04:22', durationSec: 262, coffeePairing: 'Cà phê Trứng Hà Nội' },
        ],
      },
    ],
  },
  {
    id: 'slot-evening',
    slotNumber: 'SLOT #4',
    name: 'Không Khí Buổi Tối & Chill Sau Giờ Làm',
    timeRange: '3 PM – 10 PM',
    description: 'Hiện đại và ấm áp. Những ca khúc thịnh hành cho buổi tối gắn kết.',
    accentColor: '#A855F7',
    badgeBg: '#202026',
    badgeText: '#C084FC',
    playlists: [
      {
        id: 'v-pop-ngay-hom-qua',
        title: 'V-Pop Ngày Hôm Qua',
        slotId: 'slot-evening',
        slotName: '3 PM – 10 PM',
        description: 'Hoài niệm thanh xuân.',
        trackCount: 38,
        duration: '2h 45m',
        icon: 'fa-heart',
        accentColor: '#A855F7',
        tracks: [
          { id: 't-29', title: 'Cơn Mưa Ngang Qua (Unplugged)', artist: 'M-TP Acoustic', duration: '03:40', durationSec: 220, coffeePairing: 'Cà phê Cốt Dừa' },
          { id: 't-30', title: 'Nơi Này Có Anh (Jazz Version)', artist: 'Gate 7 Live Band', duration: '04:15', durationSec: 255, coffeePairing: 'Irish Coffee' },
        ],
      },
      {
        id: 'late-night-beats',
        title: 'Late Night Beats',
        slotId: 'slot-evening',
        slotName: '3 PM – 10 PM',
        description: 'Thị thành ánh đèn đêm.',
        trackCount: 44,
        duration: '3h 10m',
        icon: 'fa-moon',
        accentColor: '#A855F7',
        tracks: [
          { id: 't-31', title: 'Neon Reflections in Hoan Kiem', artist: 'Nightline G7', duration: '03:33', durationSec: 213, coffeePairing: 'Cold Brew Tonic' },
        ],
      },
      {
        id: 'night-pop',
        title: 'Night Pop',
        slotId: 'slot-evening',
        slotName: '3 PM – 10 PM',
        description: 'Thịnh hành quốc tế.',
        trackCount: 30,
        duration: '2h 20m',
        icon: 'fa-star',
        accentColor: '#A855F7',
        tracks: [
          { id: 't-32', title: 'Midnight City (Slowed Chill)', artist: 'Retro Soundstage', duration: '04:02', durationSec: 242, coffeePairing: 'Espresso Martini Không Cồn' },
        ],
      },
      {
        id: 'evening-jazz',
        title: 'Evening Jazz',
        slotId: 'slot-evening',
        slotName: '3 PM – 10 PM',
        description: 'Ấm áp & lãng mạn.',
        trackCount: 50,
        duration: '3h 30m',
        icon: 'fa-wine-glass',
        accentColor: '#A855F7',
        tracks: [
          { id: 't-33', title: 'Autumn Leaves Over West Lake', artist: 'Hanoi Jazz Quartet', duration: '04:50', durationSec: 290, coffeePairing: 'Cà phê Kem Khói' },
        ],
      },
    ],
  },
];

export const INITIAL_REQUESTS: RequestTicket[] = [
  {
    id: 'req-1',
    songTitle: 'Có Những Ngày Ơi',
    artist: 'Trần Duy Đạt',
    tableLocation: 'Bàn 04 • V-Indie Acoustic',
    status: 'next',
    requestedAt: '11:15',
    queueNumber: 1,
  },
  {
    id: 'req-2',
    songTitle: 'Autumn in Hanoi (Acoustic)',
    artist: 'Quán Nhạc G7',
    tableLocation: 'Quầy Bar Roaster G7',
    status: 'queued',
    requestedAt: '11:18',
    queueNumber: 2,
  },
  {
    id: 'req-3',
    songTitle: 'Tách Cà Phê Số 7',
    artist: 'Hà Anh Tuấn Cover',
    tableLocation: 'Bàn 12 • Không gian Tầng 2',
    status: 'queued',
    requestedAt: '11:22',
    queueNumber: 3,
  },
];

export const COFFEE_PAIRINGS = [
  {
    drink: 'Cà phê Muối Gate 7',
    bestGenre: 'V-Indie Acoustic',
    description: 'Lớp kem béo đậm vị cân bằng cùng giai điệu mộc mạc của guitar gỗ và ca từ tự sự.',
    tags: ['Đậm đà', 'Hoài niệm', '72dB'],
  },
  {
    drink: 'Pour-over V60 Ethiopia Yirgacheffe',
    bestGenre: 'Lo-fi Chill / Ambient',
    description: 'Hương hoa nhài và cam bergamot tỏa sáng cùng tiếng click-hiss của băng từ analog.',
    tags: ['Hương hoa', 'Sáng vị', 'Tập trung'],
  },
  {
    drink: 'Cold Brew Mơ Rừng & Cam Vàng',
    bestGenre: 'Indie Pop / Chillhop',
    description: 'Vị chua thanh sảng khoái đánh thức mọi giác quan cùng những nhịp bass nảy tươi mới.',
    tags: ['Tươi mát', 'Năng lượng', 'Sáng tạo'],
  },
  {
    drink: 'Espresso Con Panna Thảo Mộc',
    bestGenre: 'Bossa Nova & Evening Jazz',
    description: 'Hậu vị ca cao nồng ấm hòa với nhịp kèn saxophone êm dịu khi ánh đèn vàng lên phố.',
    tags: ['Nồng nàn', 'Lãng mạn', 'Thư thái'],
  },
];
